# Legacy labeler configuration file
# This file is kept for reference but is no longer actively used
# The auto-labeling logic is now embedded directly in the GitHub Actions workflow
# using actions/github-script for better control and issue-based labeling

# Note: If you need to use actions/labeler in the future for PR file-based labeling,
# you can restore the v5 format configuration here